"use client";

import AboutService from "@/components/about-service/about-service";
import AddOnCard from "@/components/add-on-card/add-on-card";
import BeforeAfterGallery from "@/components/before-after-gallery/before-after-gallery";
import FaqItem from "@/components/faq-item/faq-item";
import Hero from "@/components/hero/hero";
import { useLanguage } from "@/components/language-provider/language-provider";
import MediaCard from "@/components/media-card/media-card";
import MobileCarousel from "@/components/mobile-carousel/mobile-carousel";
import PackageCard from "@/components/package-card/package-card";
import PrimaryLink from "@/components/primary-link/primary-link";
import ProcessStep from "@/components/process-step/process-step";
import ProcessStepGallery from "@/components/process-step-gallery/process-step-gallery";
import Reveal from "@/components/reveal/reveal";
import ServiceCard from "@/components/service-card/service-card";
import ServiceAreaMap from "@/components/service-area-map/service-area-map";
import SiteFooter from "@/components/site-footer/site-footer";
import SiteHeader from "@/components/site-header/site-header";
import TestimonialCarousel from "@/components/testimonial-carousel/testimonial-carousel";

const images = [
  { variant: "large" as const, position: "center", src: "https://images.unsplash.com/photo-1746593934498-b335e4e04845?auto=format&fit=crop&q=85&w=1800", credit: "Srinivasa Yadav", creditHref: "https://unsplash.com/photos/black-car-in-a-modern-car-wash-p8wO38qEIhk" },
  { variant: "small" as const, position: "center", src: "https://images.unsplash.com/photo-1769641156607-16833781bc16?auto=format&fit=crop&q=85&w=1400", credit: "Avenir Visuals", creditHref: "https://unsplash.com" },
  { variant: "small" as const, position: "center", src: "https://images.unsplash.com/photo-1761312834150-4beefff097a7?auto=format&fit=crop&q=85&w=1400", credit: "Willian Cittadin", creditHref: "https://unsplash.com" },
];
const serviceImages = [{ variant: "large" as const, position: "center", src: "https://images.unsplash.com/photo-1605437241278-c1806d14a4d9?fit=crop&fm=webp&q=80&w=1200", credit: "Ján Vlačuha", creditHref: "https://unsplash.com", unoptimized: true }, { variant: "small" as const, position: "center", src: "https://images.unsplash.com/photo-1708805282683-50a060eba80f?fit=crop&fm=webp&q=80&w=1200", credit: "Zac Nielson", creditHref: "https://unsplash.com" }];
const comparison = { before: { alt: "Car during washing", credit: "mintosko", creditHref: "https://unsplash.com", src: "https://images.unsplash.com/photo-1633014041037-f5446fb4ce99?auto=format&fit=crop&q=85&w=2200" }, after: { alt: "Finished vehicle", credit: "Srinivasa Yadav", creditHref: "https://unsplash.com", src: "https://images.unsplash.com/photo-1746593934498-b335e4e04845?auto=format&fit=crop&q=85&w=2200" } };

const localized = {
  en: { about: ["About Elite", "Car care,", "made mobile.", "Belgium-based car wash and auto detailing. At home, we can care for the whole vehicle; at an office, we focus on interior detailing that fits around your day."], statement: ["Built around the appointment", "We arrive prepared, assess the vehicle with you and focus on the work that makes the biggest difference. From a fresh wash to a full detail or headlight polish, the standard stays considered.", "View our services"], services: ["Our services", "Everything your car ", "needs.", "From regular upkeep to complete transformation, every service is adapted to the condition of your vehicle."], items: [["01", "Car Wash", "A safe exterior wash that refreshes paintwork, glass, wheels and finishing details."], ["02", "Interior Detail", "A deep reset for seats, carpets, trim and the surfaces you use every day."], ["03", "Full Detail", "A complete interior-and-exterior treatment for a vehicle that needs a proper reset."], ["04", "Headlight Polish", "Cleaning and polishing for clearer headlight lenses."], ["05", "Sale Preparation", "Presentation-led care that helps your vehicle make the right first impression."]], process: ["How it works", "Four simple", "steps.", "Clear communication, careful work and no unnecessary waiting rooms."], steps: [["01", "Tell us about your car", "Share the vehicle, location and result you are looking for."], ["02", "Choose a time and place", "We confirm the right service and arrange a convenient appointment."], ["03", "We detail on location", "Our mobile setup arrives ready with the products and equipment needed."], ["04", "Enjoy the finish", "We complete a final inspection before handing your refreshed vehicle back."]], faq: ["Questions, answered", "Before we", "get started."], faqs: [["Do I need to provide water or electricity?", "Tell us what is available when booking. We will confirm the setup required."], ["How long does a detail take?", "Most appointments take between two and five hours."], ["Where in Belgium do you operate?", "We primarily serve Brussels, Flemish Brabant and Walloon Brabant."], ["Can you detail my car at work?", "Yes, with permission and enough safe working space."]], testimonial: ["Testimonials", "Trusted for the", "details.", "Feedback from owners and businesses who choose mobile care at their home or workplace."], contact: ["Ready for a", "better finish?", "Tell us about your vehicle and we'll recommend the right service.", "Request a booking"] },
  fr: { about: ["À propos", "L'entretien auto,", "chez vous.", "Lavage auto et detailing mobile en Belgique. À domicile, nous entretenons l'ensemble du véhicule ; au bureau, nous nous concentrons sur l'intérieur pour respecter votre journée."], statement: ["Pensé autour du rendez-vous", "Nous arrivons équipés, examinons le véhicule avec vous et ciblons ce qui fera la plus grande différence. Lavage, detailing complet ou rénovation des phares : chaque intervention est réalisée avec soin.", "Voir nos services"], services: ["Nos services", "Tout ce dont votre voiture ", "a besoin.", "De l'entretien régulier à la remise à neuf complète, chaque service est adapté à l'état de votre véhicule."], items: [["01", "Lavage auto", "Un lavage extérieur sûr pour la carrosserie, les vitres, les roues et les finitions."], ["02", "Detailing intérieur", "Un nettoyage profond des sièges, tapis, garnitures et surfaces du quotidien."], ["03", "Detailing complet", "Un traitement intérieur et extérieur complet pour donner un vrai coup de neuf."], ["04", "Polissage des phares", "Nettoyage et polissage pour des optiques plus nets."], ["05", "Préparation à la vente", "Un soin axé sur la présentation pour une meilleure première impression."]], process: ["Comment ça marche", "Quatre étapes", "simples.", "Une communication claire, un travail soigné et aucun temps perdu en salle d'attente."], steps: [["01", "Parlez-nous de votre véhicule", "Indiquez le véhicule, le lieu et le résultat que vous recherchez."], ["02", "Choisissez un créneau et un lieu", "Nous confirmons le bon service et organisons un rendez-vous pratique."], ["03", "Nous intervenons sur place", "Notre équipe mobile arrive avec les produits et l'équipement nécessaires."], ["04", "Profitez du résultat", "Nous réalisons un contrôle final avant de vous restituer votre véhicule."],], faq: ["Vos questions", "Avant de", "commencer."], faqs: [["Dois-je fournir de l'eau ou de l'électricité ?", "Indiquez-nous ce qui est disponible lors de la réservation."], ["Combien de temps dure un detailing ?", "La plupart des rendez-vous durent entre deux et cinq heures."], ["Où intervenez-vous en Belgique ?", "Nous desservons Bruxelles, le Brabant flamand et le Brabant wallon."], ["Pouvez-vous intervenir sur mon lieu de travail ?", "Oui, avec autorisation et un espace de travail sûr."]], testimonial: ["Témoignages", "La confiance dans", "les détails.", "Les retours de particuliers et d'entreprises qui choisissent notre soin mobile, à domicile ou au travail."], contact: ["Prêt pour une", "meilleure finition ?", "Parlez-nous de votre véhicule : nous vous recommanderons le service adapté.", "Demander une réservation"] },
};

const Page = () => {
  const { language } = useLanguage(); const t = localized[language];
  const testimonials = language === "fr" ? [{ quote: "La voiture était complètement rafraîchie, sans que j'aie besoin de quitter mon domicile.", source: "Client particulier", location: "Bruxelles" }, { quote: "Communication claire, travail soigné et résultat au-delà de mes attentes.", source: "Client particulier", location: "Brabant flamand" }, { quote: "Un service pratique pour nos véhicules d'entreprise.", source: "Client professionnel", location: "Brabant wallon" }] : [{ quote: "The car felt completely refreshed, and I did not have to leave home for the appointment.", source: "Private client", location: "Brussels" }, { quote: "Clear communication, careful work and a finish that exceeded expectations.", source: "Private client", location: "Flemish Brabant" }, { quote: "A convenient service for our company vehicles with consistent attention to detail.", source: "Business client", location: "Walloon Brabant" }];
  const packages: [string, string, string, string[]][] = language === "fr" ? [["À partir de 95 €", "Rafraîchissement intérieur", "Un nettoyage complet de l'habitacle.", ["Aspiration et surfaces", "Sièges, tapis et garnitures", "Vitres et finition"]], ["À partir de 145 €", "Detailing complet", "Un rendez-vous intérieur et extérieur complet.", ["Intérieur inclus", "Lavage à la main", "Protection extérieure"]], ["À partir de 220 €", "Detailing signature", "Une transformation plus poussée.", ["Traitement intérieur", "Soin extérieur renforcé", "Contrôle final"]]] : [["From €95", "Interior Refresh", "A thorough reset for the cabin.", ["Vacuum and surface clean", "Seats, carpets and trim", "Windows and finishing touches"]], ["From €145", "Complete Detail", "A balanced inside-and-out appointment.", ["Interior Refresh included", "Hand wash", "Exterior protection"]], ["From €220", "Signature Detail", "A considered transformation.", ["Deep interior treatment", "Enhanced exterior care", "Final inspection"]]];
  return <main><SiteHeader /><Hero /><section className="about light-section" id="about"><div className="shell"><Reveal className="about__heading" direction="left"><div><p className="section-label">{t.about[0]}</p><h2>{t.about[1]}<br /><span>{t.about[2]}</span></h2></div><p>{t.about[3]}</p></Reveal><div className="about__body"><Reveal className="about__statement" delay={100} direction="left"><span>{t.statement[0]}</span><p>{t.statement[1]}</p><PrimaryLink href="#services">{t.statement[2]}</PrimaryLink></Reveal><Reveal className="about__service-list" delay={160}>{[["01", language === "fr" ? "Lavage auto" : "Car wash"], ["02", language === "fr" ? "Detailing auto" : "Auto detailing"], ["03", language === "fr" ? "Soin des phares" : "Headlight care"]].map(([n,title]) => <AboutService description="" key={n} number={n} title={title} />)}</Reveal></div></div></section><ServiceAreaMap />
  <section className="services light-section" id="services"><div className="shell"><Reveal className="section-top"><div><p className="section-label">{t.services[0]}</p><h2>{t.services[1]}<span>{t.services[2]}</span></h2></div><p>{t.services[3]}</p></Reveal><Reveal className="service-grid">{t.items.map(([n,title,d])=><ServiceCard description={d} key={n} number={n} title={title} />)}</Reveal><Reveal className="service-media-grid">{serviceImages.map((image,i)=><MediaCard {...image} key={i} label={language === "fr" ? ["Soin intérieur","Détail des roues"][i] : ["Interior care","Wheel detail"][i]} title={language === "fr" ? ["Un habitacle remis à neuf", "Une attention aux détails"][i] : ["A cabin reset", "Care through every detail"][i]} />)}</Reveal></div></section>
  <section className="packages" id="pricing"><div className="shell"><Reveal className="section-top section-top--dark"><div><p className="section-label">{language === "fr" ? "Forfaits" : "Price packages"}</p><h2>{language === "fr" ? "Un soin clair." : "Clear care."}<br /><span>{language === "fr" ? "Des prix clairs." : "Clear pricing."}</span></h2></div><p>{language === "fr" ? "Des prix de départ clairs avant la confirmation de votre rendez-vous." : "Clear starting prices before we confirm your appointment."}</p></Reveal><MobileCarousel ariaLabel="Price packages">{packages.map(([l,title,d,f])=><PackageCard description={d} features={f} key={title} label={l} title={title} />)}</MobileCarousel><div className="add-ons__intro"><div><p className="section-label">{language === "fr" ? "Options" : "Optional extras"}</p><h3>{language === "fr" ? "Ajoutez le détail" : "Add the detail"}<br /><span>{language === "fr" ? "qui compte." : "that matters."}</span></h3></div></div><MobileCarousel ariaLabel="Add-ons">{(language === "fr" ? [["Nettoyage moteur","Un nettoyage soigné sous le capot.","À partir de 35 €"],["Poils d'animaux","Pour les poils incrustés.","À partir de 30 €"],["Rénovation des phares","Pour des optiques plus nets.","À partir de 60 €"]] : [["Engine bay detail","A careful clean beneath the bonnet.","From €35"],["Pet hair removal","For embedded pet hair.","From €30"],["Headlight restoration","Clearer headlight lenses.","From €60"]]).map(([title,d,p])=><AddOnCard description={d} key={title} price={p} title={title} />)}</MobileCarousel></div></section>
  <section className="works shell" id="works"><Reveal className="section-top section-top--dark"><div><p className="section-label">{language === "fr" ? "Nos réalisations" : "Our works"}</p><h2>{language === "fr" ? "Un soin qui se" : "Care you can"}<br /><span>{language === "fr" ? "voit." : "see."}</span></h2></div></Reveal><Reveal className="work-grid">{images.map((image,i)=><MediaCard {...image} key={i} label={language === "fr" ? ["Détail extérieur","Processus de lavage","Soin carrosserie"][i] : ["Exterior detail","Wash process","Paintwork care"][i]} title={language === "fr" ? ["Soin extérieur approfondi","Traitement mousse doux","Une finition à protéger"][i] : ["Deep exterior care","Safe foam treatment","A finish worth protecting"][i]} />)}</Reveal><BeforeAfterGallery {...comparison} /></section>
  <section className="process light-section" id="process"><div className="shell process__layout"><div className="process__intro"><p className="section-label">{t.process[0]}</p><h2>{t.process[1]}<br /><span>{t.process[2]}</span></h2><p>{t.process[3]}</p></div><div className="process__steps">{t.steps.map(([n,title,d])=><ProcessStep description={d} key={n} number={n} title={title} />)}</div></div><ProcessStepGallery /></section>
  <section className="faq shell" id="faq"><div className="faq__intro"><p className="section-label">{t.faq[0]}</p><h2>{t.faq[1]}<br /><span>{t.faq[2]}</span></h2></div><div className="faq__list">{t.faqs.map(([q,a])=><FaqItem answer={a} key={q} question={q} />)}</div></section><section className="testimonials light-section" id="testimonials"><div className="shell"><div className="section-top"><div><p className="section-label">{t.testimonial[0]}</p><h2>{t.testimonial[1]}<br /><span>{t.testimonial[2]}</span></h2></div><p>{t.testimonial[3]}</p></div><TestimonialCarousel testimonials={testimonials} /></div></section><section className="contact-band" id="contact"><div className="shell contact-band__inner"><div><p>Elite Auto Studio</p><h2>{t.contact[0]}<br /><span>{t.contact[1]}</span></h2></div><div><p>{t.contact[2]}</p><PrimaryLink href="mailto:hello@eliteautostudio.be" track={{ event: "booking_click", params: { location: "contact_band" } }}>{t.contact[3]}</PrimaryLink></div></div></section><SiteFooter /></main>;
};

export default Page;
